FROM golang:1.22.4-alpine3.20 AS builder

LABEL description="watch-informer" \
      maintainer="Casey Wylie casewylie@gmail.com"

WORKDIR /app
COPY . .
RUN go mod download && go mod verify
RUN GOARCH=amd64 CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o watch-informer main.go

FROM scratch
WORKDIR /app
COPY --from=builder /app/watch-informer ./

ENTRYPOINT ["./watch-informer"]
