apiVersion: v1
kind: Pod
metadata:
  name: curler
  namespace: watch-informer
  labels: 
    app: curler
spec:
  serviceAccountName: watch-informer
  containers:
  - name: grpcurl
    image: curler:ci
    imagePullPolicy: Never

