// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.3
// source: api/apiv1.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WatcherClient is the client API for Watcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatcherClient interface {
	StartWatch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*WatchResponse, error)
	WatchEvents(ctx context.Context, opts ...grpc.CallOption) (Watcher_WatchEventsClient, error)
}

type watcherClient struct {
	cc grpc.ClientConnInterface
}

func NewWatcherClient(cc grpc.ClientConnInterface) WatcherClient {
	return &watcherClient{cc}
}

func (c *watcherClient) StartWatch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*WatchResponse, error) {
	out := new(WatchResponse)
	err := c.cc.Invoke(ctx, "/api.Watcher/StartWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watcherClient) WatchEvents(ctx context.Context, opts ...grpc.CallOption) (Watcher_WatchEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Watcher_ServiceDesc.Streams[0], "/api.Watcher/WatchEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &watcherWatchEventsClient{stream}
	return x, nil
}

type Watcher_WatchEventsClient interface {
	Send(*EventRequest) error
	Recv() (*ResourceEvent, error)
	grpc.ClientStream
}

type watcherWatchEventsClient struct {
	grpc.ClientStream
}

func (x *watcherWatchEventsClient) Send(m *EventRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *watcherWatchEventsClient) Recv() (*ResourceEvent, error) {
	m := new(ResourceEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WatcherServer is the server API for Watcher service.
// All implementations must embed UnimplementedWatcherServer
// for forward compatibility
type WatcherServer interface {
	StartWatch(context.Context, *WatchRequest) (*WatchResponse, error)
	WatchEvents(Watcher_WatchEventsServer) error
	mustEmbedUnimplementedWatcherServer()
}

// UnimplementedWatcherServer must be embedded to have forward compatible implementations.
type UnimplementedWatcherServer struct {
}

func (UnimplementedWatcherServer) StartWatch(context.Context, *WatchRequest) (*WatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWatch not implemented")
}
func (UnimplementedWatcherServer) WatchEvents(Watcher_WatchEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedWatcherServer) mustEmbedUnimplementedWatcherServer() {}

// UnsafeWatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatcherServer will
// result in compilation errors.
type UnsafeWatcherServer interface {
	mustEmbedUnimplementedWatcherServer()
}

func RegisterWatcherServer(s grpc.ServiceRegistrar, srv WatcherServer) {
	s.RegisterService(&Watcher_ServiceDesc, srv)
}

func _Watcher_StartWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServer).StartWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Watcher/StartWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServer).StartWatch(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watcher_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WatcherServer).WatchEvents(&watcherWatchEventsServer{stream})
}

type Watcher_WatchEventsServer interface {
	Send(*ResourceEvent) error
	Recv() (*EventRequest, error)
	grpc.ServerStream
}

type watcherWatchEventsServer struct {
	grpc.ServerStream
}

func (x *watcherWatchEventsServer) Send(m *ResourceEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *watcherWatchEventsServer) Recv() (*EventRequest, error) {
	m := new(EventRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Watcher_ServiceDesc is the grpc.ServiceDesc for Watcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Watcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Watcher",
	HandlerType: (*WatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWatch",
			Handler:    _Watcher_StartWatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _Watcher_WatchEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/apiv1.proto",
}
